// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: sfposahqskcirpmfwmgh

class SupabaseConfig {
  static const String supabaseUrl = 'https://sfposahqskcirpmfwmgh.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcG9zYWhxc2tjaXJwbWZ3bWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Njk3NjYsImV4cCI6MjA3NDE0NTc2Nn0.qpKVNxCAQl7dW8TipUBFpd48mVD6GgVNi_LmX9pmq8A';
}
